const COLOR_WHITE = 'WHITE';
const COLOR_BLACK = 'BLACK';

const PLAYERS = {
  '': {name: 'Unknown', rating: 'N/A'},
  '*GM_CARLSEN': {name: 'GM Carlsen', rating: 2842},
  '*GM_NAKAMURA': {name: 'GM Nakamura', rating: 2836},
  '*GM_DUDA': {name: 'GM Duda', rating: 2801},
  '*GM_NEPOMNIACHT': {name: 'GM Nepomniachtchi', rating: 2798},
  '*GM_VACHIER-LAG': {name: 'GM Vachier-Lagrave', rating: 2773},
  '*GM_CARUANA': {name: 'GM Caruana', rating: 2770},
  '*GM_GIRI': {name: 'GM Giri', rating: 2767},
  '*GM_GRISCHUK': {name: 'GM Grischuk', rating: 2763},
  '*GM_KARJAKIN': {name: 'GM Karjakin', rating: 2757},
  '*GM_SVIDLER': {name: 'GM Svidler', rating: 2752},
  '*GM_RAPPORT': {name: 'GM Rapport', rating: 2750},
  '*GM_WOJTASZEK': {name: 'GM Wojtaszek', rating: 2743},
  '*GM_DUBOV': {name: 'GM Dubov', rating: 2735},
  '*GM_ARONIAN': {name: 'GM Aronian', rating: 2728},
  '*GM_MAMEDYAROV': {name: 'GM Mamedyarov', rating: 2727},
  '*GM_OPARIN': {name: 'GM Oparin', rating: 2725},
  '*GM_ARTEMIEV': {name: 'GM Artemiev', rating: 2714},
  '*GM_MOTYLEV': {name: 'GM Motylev', rating: 2703},
  '*GM_SHIROV': {name: 'GM Shirov', rating: 2702},
  '*GM_SARGISSIAN': {name: 'GM Sargissian', rating: 2693},
  '*GM_FEDOSEEV': {name: 'GM Fedoseev', rating: 2692},
  '*GM_MAMEDOV': {name: 'GM Mamedov', rating: 2690},
  '*GM_KOROBOV': {name: 'GM Korobov', rating: 2689},
  '*GM_ONYSHCHUK': {name: 'GM Onyshchuk', rating: 2687},
  '*GM_SARIC': {name: 'GM Saric', rating: 2684},
  '*GM_SARANA': {name: 'GM Sarana', rating: 2680},
  '*GM_JOBAVA': {name: 'GM Jobava', rating: 2679},
  '*GM_SVANE': {name: 'GM Svane', rating: 2677},
  '*GM_PARAVYAN': {name: 'GM Paravyan', rating: 2671},
  '*GM_MOVSESIAN': {name: 'GM Movsesian', rating: 2667},
  '*GM_DEMCHENKO': {name: 'GM Demchenko', rating: 2666},
  '*GM_SMIRIN': {name: 'GM Smirin', rating: 2663},
  '*GM_FIROUZJA': {name: 'GM Firouzja', rating: 2656},
  '*GM_MATLAKOV': {name: 'GM Matlakov', rating: 2652},
  '*GM_GELFAND': {name: 'GM Gelfand', rating: 2648},
  '*GM_KOVALEV': {name: 'GM Kovalev', rating: 2647},
  '*GM_ANTIPOV': {name: 'GM Antipov', rating: 2644},
  '*GM_ALEKSEENKO': {name: 'GM Alekseenko', rating: 2637},
  '*GM_ITURRIZAGA_': {name: 'GM Iturrizaga Bonelli', rating: 2634},
  '*GM_SJUGIROV': {name: 'GM Sjugirov', rating: 2634},
  '*GM_RIAZANTSEV': {name: 'GM Riazantsev', rating: 2632},
  '*GM_VOLOKITIN': {name: 'GM Volokitin', rating: 2631},
  '*GM_PREDKE': {name: 'GM Predke', rating: 2630},
  '*GM_VIDIT': {name: 'GM Vidit', rating: 2629},
  '*GM_ANTON_GUIJA': {name: 'GM Anton Guijarro', rating: 2627},
  '*GM_HOWELL': {name: 'GM Howell', rating: 2624},
  '*GM_CHEPARINOV': {name: 'GM Cheparinov', rating: 2621},
  '*GM_DREEV': {name: 'GM Dreev', rating: 2621},
  '*GM_PETROSIAN': {name: 'GM Petrosian', rating: 2621},
  '*GM_SANTOS_LATA': {name: 'GM Santos Latasa', rating: 2618},
  '*GM_HEIMANN': {name: 'GM Heimann', rating: 2616},
  '*GM_PONKRATOV': {name: 'GM Ponkratov', rating: 2614},
  '*GM_HOVHANNISYA': {name: 'GM Hovhannisyan', rating: 2613},
  '*GM_EFIMENKO': {name: 'GM Efimenko', rating: 2609},
  '*GM_CHIGAEV': {name: 'GM Chigaev', rating: 2605},
  '*GM_ADLY': {name: 'GM Adly', rating: 2597},
  '*GM_ABDUSATTORO': {name: 'GM Abdusattorov', rating: 2593},
  '*GM_TIMOFEEV': {name: 'GM Timofeev', rating: 2591},
  '*GM_QUPARADZE': {name: 'GM Quparadze', rating: 2583},
  '*GM_GAREYEV': {name: 'GM Gareyev', rating: 2578},
  '*GM_HALKIAS': {name: 'GM Halkias', rating: 2576},
  '*GM_BLUEBAUM': {name: 'GM Bluebaum', rating: 2575},
  '*GM_TER-SAHAKYA': {name: 'GM Ter-Sahakyan', rating: 2573},
  '*GM_VAKHIDOV': {name: 'GM Vakhidov', rating: 2566},
  '*GM_NAJER': {name: 'GM Najer', rating: 2565},
  '*GM_VAN_FOREEST': {name: 'GM Van Foreest', rating: 2563},
  '*GM_JUMABAYEV': {name: 'GM Jumabayev', rating: 2562},
  '*GM_SOCKO': {name: 'GM Socko', rating: 2562},
  '*GM_CORRALES_JI': {name: 'GM Corrales Jimenez', rating: 2561},
  '*GM_THEODOROU': {name: 'GM Theodorou', rating: 2559},
  '*GM_GHAEM_MAGHA': {name: 'GM Ghaem Maghami', rating: 2553},
  '*GM_KOZAK': {name: 'GM Kozak', rating: 2552},
  '*GM_DVIRNYY': {name: 'GM Dvirnyy', rating: 2550},
  '*GM_PARLIGRAS': {name: 'GM Parligras', rating: 2550},
  '*GM_SHOKER': {name: 'GM Shoker', rating: 2550},
  '*GM_PIORUN': {name: 'GM Piorun', rating: 2547},
  '*GM_VOKHIDOV': {name: 'GM Vokhidov', rating: 2546},
  '*GM_DEMIDOV': {name: 'GM Demidov', rating: 2544},
  '*GM_INDJIC': {name: 'GM Indjic', rating: 2544},
  '*GM_BARTEL': {name: 'GM Bartel', rating: 2543},
  '*GM_KOBALIA': {name: 'GM Kobalia', rating: 2543},
  '*GM_FRIDMAN': {name: 'GM Fridman', rating: 2542},
  '*GM_KADRIC': {name: 'GM Kadric', rating: 2542},
  '*GM_TARI': {name: 'GM Tari', rating: 2542},
  '*GM_ZVJAGINSEV': {name: 'GM Zvjaginsev', rating: 2539},
  '*GM_GAGUNASHVIL': {name: 'GM Gagunashvili', rating: 2538},
  '*GM_DONCHENKO': {name: 'GM Donchenko', rating: 2535},
  '*GM_GABUZYAN': {name: 'GM Gabuzyan', rating: 2535},
  '*GM_MASTROVASIL': {name: 'GM Mastrovasilis', rating: 2534},
  '*IM_MURZIN': {name: 'IM Murzin', rating: 2523},
  '*GM_OLEKSIYENKO': {name: 'GM Oleksiyenko', rating: 2523},
  '*GM_PICHOT': {name: 'GM Pichot', rating: 2523},
  '*GM_CHRISTIANSE': {name: 'GM Christiansen', rating: 2522},
  '*GM_MORONI': {name: 'GM Moroni', rating: 2519},
  '*GM_MICHALIK': {name: 'GM Michalik', rating: 2515},
  '*GM_PETROSYAN': {name: 'GM Petrosyan', rating: 2514},
  '*GM_YUFFA': {name: 'GM Yuffa', rating: 2514},
  '*GM_MAGHSOODLOO': {name: 'GM Maghsoodloo', rating: 2512},
  '*GM_OLAFSSON': {name: 'GM Olafsson', rating: 2509},
  '*GM_SANAL': {name: 'GM Sanal', rating: 2509},
  '*GM_SHEVCHENKO': {name: 'GM Shevchenko', rating: 2508},
  '*GM_LIMA': {name: 'GM Lima', rating: 2505},
  '*GM_NIHAL_SARIN': {name: 'GM Nihal Sarin', rating: 2500},
  '*GM_GAJEWSKI': {name: 'GM Gajewski', rating: 2496},
  '*GM_NGUYEN': {name: 'GM Nguyen', rating: 2488},
  '*GM_HARSHA_BHAR': {name: 'GM Harsha Bharathakoti', rating: 2484},
  '*GM_NARAYANAN.S': {name: 'GM Narayanan.S.L', rating: 2482},
  '*GM_ZILKA': {name: 'GM Zilka', rating: 2474},
  '*GM_PURANIK': {name: 'GM Puranik', rating: 2472},
  '*IM_FAIZRAKHMAN': {name: 'IM Faizrakhmanov', rating: 2461},
  '*GM_SYCHEV': {name: 'GM Sychev', rating: 2461},
  '*GM_POSTNY': {name: 'GM Postny', rating: 2454},
  '*GM_SADHWANI': {name: 'GM Sadhwani', rating: 2454},
  '*IM_COSTACHI': {name: 'IM Costachi', rating: 2443},
  '*GM_HEBERLA': {name: 'GM Heberla', rating: 2437},
  '*GM_CARLSSON': {name: 'GM Carlsson', rating: 2436},
  '*IM_SAHIDI': {name: 'IM Sahidi', rating: 2436},
  '*IM_AZIZ': {name: 'IM Aziz', rating: 2430},
  '*GM_KRASENKOW': {name: 'GM Krasenkow', rating: 2430},
  '*GM_TANG': {name: 'GM Tang', rating: 2427},
  '*GM_NEVEDNICHY': {name: 'GM Nevednichy', rating: 2425},
  '*GM_DZIUBA': {name: 'GM Dziuba', rating: 2424},
  '*GM_CUENCA_JIME': {name: 'GM Cuenca Jimenez', rating: 2421},
  '*IM_SARACI': {name: 'IM Saraci', rating: 2414},
  '*IM_AL_QUDAIMI': {name: 'IM Al Qudaimi', rating: 2412},
  '*IM_PENG': {name: 'IM Peng', rating: 2411},
  '*IM_BLOHBERGER': {name: 'IM Blohberger', rating: 2409},
  '*GM_DRAGNEV': {name: 'GM Dragnev', rating: 2409},
  '*IM_HOLM': {name: 'IM Holm', rating: 2409},
  '*GM_THYBO': {name: 'GM Thybo', rating: 2401},
  '*GM_ERIGAISI_AR': {name: 'GM Erigaisi Arjun', rating: 2397},
  '*IM_VASTRUKHIN': {name: 'IM Vastrukhin', rating: 2382},
  '*GM_MARTIROSYAN': {name: 'GM Martirosyan', rating: 2377},
  '*GM_MIKHALEVSKI': {name: 'GM Mikhalevski', rating: 2366},
  '*IM_ROSNER': {name: 'IM Rosner', rating: 2363},
  '*GM_IVIC': {name: 'GM Ivic', rating: 2357},
  '*IM_TISSIR': {name: 'IM Tissir', rating: 2354},
  '*GM_SINDAROV': {name: 'GM Sindarov', rating: 2353},
  '*GM_SARGSYAN': {name: 'GM Sargsyan', rating: 2344},
  '*GM_NIEMANN': {name: 'GM Niemann', rating: 2327},
  '*GM_ASADLI': {name: 'GM Asadli', rating: 2309},
  '*IM_TOLOGONTEGI': {name: 'IM Tologontegin', rating: 2300},
  '*IM_MACEDO': {name: 'IM Macedo', rating: 2293},
  '*IM_MURADLI': {name: 'IM Muradli', rating: 2285},
  '*CM_PETROVSKYI': {name: 'CM Petrovskyi', rating: 2282},
  '*FM_SAMUNENKOV': {name: 'FM Samunenkov', rating: 2259},
  '*GM_SULEYMANLI': {name: 'GM Suleymanli', rating: 2202},
  '*FM_BABAZADA': {name: 'FM Babazada', rating: 2170},
  '*IM_MITRABHA': {name: 'IM Mitrabha', rating: 2107},
  '*FM_DAMJANOVIC': {name: 'FM Damjanovic', rating: 2092},
  '*GM_GUKESH_D': {name: 'GM Gukesh D', rating: 2050},
  '*N_YUNUSOV': {name: 'N Yunusov', rating: 1832},
  '*IM_ADITYA_MITT': {name: 'IM Aditya Mittal', rating: 1488}
};
Object.freeze(PLAYERS);

module.exports = {
  COLOR_WHITE,
  COLOR_BLACK,
  PLAYERS
};
