const COLOR_WHITE = 'WHITE';
const COLOR_BLACK = 'BLACK';

const PLAYERS = {
  '': {name: 'Unknown', rating: 'N/A'},
  '*GM_CARLSEN': {name: 'GM Carlsen', rating: 2842},
  '*GM_DONCHENKO': {name: 'GM Donchenko', rating: 2648},
  '*GM_DUDA': {name: 'GM Duda', rating: 2801},
  '*GM_MASTROVASIL': {name: 'GM Mastrovasilis', rating: 2534},
  '*GM_VACHIER-LAG': {name: 'GM Vachier-Lagrave', rating: 2763},
  '*GM_KLEKOWSKI': {name: 'GM Klekowski', rating: 2528},
  '*GM_GIRI': {name: 'GM Giri', rating: 2767},
  '*GM_MURZIN': {name: 'GM Murzin', rating: 2523},
  '*GM_KARJAKIN': {name: 'GM Karjakin', rating: 2757},
  '*GM_MORONI': {name: 'GM Moroni', rating: 2519},
  '*GM_WOJTASZEK': {name: 'GM Wojtaszek', rating: 2691},
  '*GM_PETROSYAN': {name: 'GM Petrosyan', rating: 2605},
  '*GM_SALEMA.R.SA': {name: 'GM Salem A.R.', rating: 2729},
  '*GM_MAGHSOODLOO': {name: 'GM Maghsoodloo', rating: 2701},
  '*GM_MAMEDYAROV': {name: 'GM Mamedyarov', rating: 2727},
  '*GM_SANALVAHAP': {name: 'GM Sanal', rating: 2509},
  '*GM_ARTEMIEV': {name: 'GM Artemiev', rating: 2714},
  '*GM_LIMADARCY': {name: 'GM Lima', rating: 2505},
  '*GM_SHIROV': {name: 'GM Shirov', rating: 2659},
  '*GM_GAJEWSKI': {name: 'GM Gajewski', rating: 2496},
  '*GM_FEDOSEEV': {name: 'GM Fedoseev', rating: 2692},
  '*GM_HARSHA': {name: 'GM Harsha', rating: 2484},
  '*GM_KOROBOV': {name: 'GM Korobov', rating: 2690},
  '*GM_ZILKA': {name: 'GM Zilka', rating: 2474},
  '*GM_SARICIVAN': {name: 'GM Saric', rating: 2644},
  '*GM_JANIKIGOR': {name: 'GM Janik', rating: 2462},
  '*GM_JOBAVA': {name: 'GM Jobava', rating: 2582},
  '*GM_FAIZRAKHMAN': {name: 'IM Faizrakhmanov', rating: 2461},
  '*GM_PARAVYAN': {name: 'GM Paravyan', rating: 2671},
  '*GM_POSTNY': {name: 'GM Postny', rating: 2454},
  '*GM_DEMCHENKO': {name: 'GM Demchenko', rating: 2666},
  '*GM_GUMULARZ': {name: 'GM Gumularz', rating: 2452},
  '*GM_FIROUZJA': {name: 'GM Firouzja', rating: 2770},
  '*GM_HEBERLA': {name: 'GM Heberla', rating: 2437},
  '*GM_GELFAND': {name: 'GM Gelfand', rating: 2680},
  '*GM_SAHIDI': {name: 'GM Sahidi', rating: 2436},
  '*GM_ANTIPOV': {name: 'GM Antipov', rating: 2644},
  '*GM_AZIZHUSAIN': {name: 'GM Aziz', rating: 2430},
  '*GM_ITURRIZAGA': {name: 'GM Iturrizaga', rating: 2634},
  '*GM_NEVEDNICHY': {name: 'GM Nevednichy', rating: 2425},
  '*GM_RIAZANTSEV': {name: 'GM Riazantsev', rating: 2632},
  '*GM_CUENCA': {name: 'GM Cuenca', rating: 2421},
  '*GM_PREDKE': {name: 'GM Predke', rating: 2630},
  '*GM_SARACI': {name: 'IM Saraci', rating: 2414},
  '*GM_ANTONGUIJAR': {name: 'GM Anton', rating: 2658},
  '*GM_PENGLIMIN': {name: 'GM Peng', rating: 2411},
  '*GM_CHEPARINOV': {name: 'GM Cheparinov', rating: 2659},
  '*GM_BLOHBERGER': {name: 'IM Blohberger', rating: 2409},
  '*GM_PETROSIAN': {name: 'GM Petrosian Tigran L.', rating: 2621},
  '*GM_THYBO': {name: 'GM Thybo', rating: 2401},
  '*GM_HEIMANN': {name: 'GM Heimann', rating: 2616},
  '*GM_BELLAHCENE': {name: 'GM Bellahcene', rating: 2397},
  '*GM_PONKRATOV': {name: 'GM Ponkratov', rating: 2614},
  '*GM_VASTRUKHIN': {name: 'IM Vastrukhin', rating: 2382},
  '*GM_EFIMENKO': {name: 'GM Efimenko', rating: 2609},
  '*GM_ERDOS': {name: 'GM Erdos', rating: 2601},
  '*GM_WIECZOREK': {name: 'GM Wieczorek', rating: 2367},
  '*GM_ABDUSATTORO': {name: 'GM Abdusattorov', rating: 2646},
  '*GM_IVIC': {name: 'GM Ivic', rating: 2606},
  '*GM_QUPARADZE': {name: 'GM Quparadze', rating: 2583},
  '*GM_NASUTA': {name: 'GM Nasuta', rating: 2345},
  '*GM_HALKIAS': {name: 'GM Halkias', rating: 2576},
  '*GM_SARGSYAN': {name: 'GM Sargsyan', rating: 2344},
  '*GM_TER-SAHAKYA': {name: 'GM Ter-Sahakyan', rating: 2607},
  '*GM_NIEMANN': {name: 'GM Niemann', rating: 2638},
  '*GM_VAKHIDOV': {name: 'GM Vakhidov', rating: 2566},
  '*GM_KUZMICZ': {name: 'GM Kuzmicz', rating: 2314},
  '*GM_VANFOREEST': {name: 'GM Van Foreest', rating: 2702},
  '*GM_VAN_FOREEST': {name: 'GM Van Foreest', rating: 2702},
  '*GM_VAN': {name: 'GM Van Foreest', rating: 2702},
  '*GM_KOSAKOWSKI': {name: 'GM Kosakowski', rating: 2304},
  '*GM_SOCKO': {name: 'GM Socko', rating: 2562},
  '*GM_KANAREK': {name: 'GM Kanarek', rating: 2296},
  '*GM_THEODOROU': {name: 'GM Theodorou', rating: 2559},
  '*GM_LUBCZYNSKI': {name: 'GM Lubczynski', rating: 2289},
  '*GM_KOZAKADAM': {name: 'GM Kozak', rating: 2552},
  '*GM_PETROVSKYI': {name: 'GM Petrovskyi', rating: 2282},
  '*GM_PARLIGRAS': {name: 'GM Parligras', rating: 2550},
  '*GM_SAMUNENKOV': {name: 'FM Samunenkov', rating: 2259},
  '*GM_PIORUN': {name: 'GM Piorun', rating: 2547},
  '*GM_TOCZEK': {name: 'GM Toczek', rating: 2220},
  '*GM_DEMIDOV': {name: 'GM Demidov', rating: 2544},
  '*GM_SULEYMANLI': {name: 'GM Suleymanli', rating: 2541},
  '*GM_BARTEL': {name: 'GM Bartel', rating: 2597},
  '*GM_BABAZADA': {name: 'FM Babazada', rating: 2170},
  '*GM_FRIDMAN': {name: 'GM Fridman', rating: 2542},
  '*GM_GUKESHD(IND': {name: 'GM Gukesh', rating: 2640},
  '*GM_TARIARYAN(N': {name: 'GM Tari', rating: 2646},
  '*GM_ADITYA': {name: 'GM Aditya', rating: 1488},
  '*GM_GAGUNASHVIL': {name: 'GM Gagunashvili', rating: 2538},
  '*GM_NAKAMURA': {name: 'GM Nakamura', rating: 2836},
  '*GM_GABUZYAN': {name: 'GM Gabuzyan', rating: 2535},
  '*GM_NEPOMNIACHT': {name: 'GM Nepomniachtchi', rating: 2798},
  '*GM_DURARBAYLI': {name: 'GM Durarbayli', rating: 2629},
  '*GM_CARUANA': {name: 'GM Caruana', rating: 2800},
  '*GM_PICHOTALAN(': {name: 'GM Pichot', rating: 2628},
  '*GM_GRISCHUK': {name: 'GM Grischuk', rating: 2763},
  '*GM_CHRISTIANSEN': {name: 'GM Christiansen', rating: 2522},
  '*GM_RAPPORT': {name: 'GM Rapport', rating: 2750},
  '*GM_MICHALIK': {name: 'GM Michalik', rating: 2515},
  '*GM_DUBOV': {name: 'GM Dubov', rating: 2735},
  '*GM_YUFFA': {name: 'GM Yuffa', rating: 2514},
  '*GM_ARONIAN': {name: 'GM Aronian', rating: 2728},
  '*GM_CZARNOTA': {name: 'GM Czarnota', rating: 2511},
  '*GM_OPARIN': {name: 'GM Oparin', rating: 2725},
  '*GM_SHEVCHENKO': {name: 'GM Shevchenko', rating: 2632},
  '*GM_HARIKRISHNA': {name: 'GM Harikrishna', rating: 2719},
  '*GM_NIHALSARIN': {name: 'GM Nihal', rating: 2652},
  '*GM_SARGISSIAN': {name: 'GM Sargissian', rating: 2664},
  '*GM_NGUYEN': {name: 'GM Nguyen', rating: 2577},
  '*GM_MAMEDOV': {name: 'GM Mamedov', rating: 2673},
  '*GM_NARAYANAN.S': {name: 'GM Narayanan', rating: 2482},
  '*GM_ONYSHCHUK': {name: 'GM Onyshchuk', rating: 2622},
  '*GM_PURANIK': {name: 'GM Puranik', rating: 2472},
  '*GM_SARANA': {name: 'GM Sarana', rating: 2680},
  '*GM_SYCHEV': {name: 'GM Sychev', rating: 2461},
  '*GM_SVANE': {name: 'GM Svane', rating: 2677},
  '*GM_KANTOR': {name: 'GM Kantor', rating: 2454},
  '*GM_MOVSESIAN': {name: 'GM Movsesian', rating: 2627},
  '*GM_SADHWANI': {name: 'GM Sadhwani', rating: 2609},
  '*GM_SMIRINILIA(': {name: 'GM Smirin', rating: 2663},
  '*GM_COSTACHI': {name: 'IM Costachi', rating: 2443},
  '*GM_MATLAKOV': {name: 'GM Matlakov', rating: 2652},
  '*GM_CARLSSON': {name: 'GM Carlsson', rating: 2436},
  '*GM_KOVALEV': {name: 'GM Kovalev', rating: 2634},
  '*GM_KRASENKOW': {name: 'GM Krasenkow', rating: 2430},
  '*GM_ALEKSEENKO': {name: 'GM Alekseenko', rating: 2637},
  '*GM_TANGANDREW(': {name: 'GM Tang', rating: 2427},
  '*GM_SJUGIROV': {name: 'GM Sjugirov', rating: 2634},
  '*GM_DZIUBA': {name: 'GM Dziuba', rating: 2424},
  '*GM_VOLOKITIN': {name: 'GM Volokitin', rating: 2652},
  '*GM_SADZIKOWSKI': {name: 'GM Sadzikowski', rating: 2414},
  '*GM_VIDIT': {name: 'GM Vidit', rating: 2629},
  '*GM_AL': {name: 'IM Al Qudaimi', rating: 2412},
  '*GM_HOWELL': {name: 'GM Howell', rating: 2658},
  '*GM_DRAGNEV': {name: 'GM Dragnev', rating: 2409},
  '*GM_DREEV': {name: 'GM Dreev', rating: 2621},
  '*GM_HOLM': {name: 'IM Holm', rating: 2409},
  '*GM_SANTOS': {name: 'GM Santos', rating: 2618},
  '*GM_JAKUBOWSKI': {name: 'GM Jakubowski', rating: 2399},
  '*GM_AMINBASSEM': {name: 'GM Amin', rating: 2614},
  '*GM_HOVHANNISYA': {name: 'GM Hovhannisyan', rating: 2622},
  '*GM_MARTIROSYAN': {name: 'GM Martirosyan Haik M.', rating: 2624},
  '*GM_CHIGAEV': {name: 'GM Chigaev', rating: 2605},
  '*GM_KOLOSOWSKI': {name: 'GM Kolosowski', rating: 2371},
  '*GM_ADLYAHMED(E': {name: 'GM Adly', rating: 2602},
  '*GM_MIKHALEVSKI': {name: 'GM Mikhalevski', rating: 2366},
  '*GM_TIMOFEEV': {name: 'GM Timofeev', rating: 2591},
  '*GM_SINDAROV': {name: 'GM Sindarov', rating: 2587},
  '*GM_GAREYEV': {name: 'GM Gareyev', rating: 2578},
  '*GM_TECLAF': {name: 'GM Teclaf', rating: 2345},
  '*GM_BLUEBAUM': {name: 'GM Bluebaum', rating: 2640},
  '*GM_BAUMJONASZ': {name: 'GM Baum', rating: 2343},
  '*GM_ALONSO': {name: 'GM Alonso', rating: 2571},
  '*GM_SZPAR': {name: 'GM Szpar', rating: 2315},
  '*GM_NAJER': {name: 'GM Najer', rating: 2565},
  '*GM_ASADLI': {name: 'GM Asadli', rating: 2309},
  '*GM_JUMABAYEV': {name: 'GM Jumabayev', rating: 2658},
  '*GM_TOLOGONTEGI': {name: 'IM Tologontegin', rating: 2300},
  '*GM_CORRALES': {name: 'GM Corrales', rating: 2561},
  '*GM_BLANCO': {name: 'GM Blanco', rating: 2289},
  '*GM_GHAEM': {name: 'GM Ghaem', rating: 2553},
  '*GM_MURADLI': {name: 'IM Muradli', rating: 2285},
  '*GM_DVIRNYY': {name: 'GM Dvirnyy', rating: 2550},
  '*GM_SANKALP': {name: 'GM Sankalp', rating: 2266},
  '*GM_SHOKERSAMY': {name: 'GM Shoker', rating: 2550},
  '*GM_DUDINGLEB': {name: 'GM Dudin', rating: 2247},
  '*GM_VOKHIDOV': {name: 'GM Vokhidov', rating: 2521},
  '*GM_KLIMKOWSKI': {name: 'GM KLIMKOWSKI', rating: 2211},
  '*GM_INDJIC': {name: 'GM Indjic', rating: 2612},
  '*GM_LOPUSIEWICZ': {name: 'GM Lopusiewicz', rating: 2197},
  '*GM_KOBALIA': {name: 'GM Kobalia', rating: 2543},
  '*GM_MITRABHA': {name: 'IM Mitrabha', rating: 2107},
  '*GM_KADRIC': {name: 'GM Kadric', rating: 2542},
  '*GM_YUNUSOV': {name: 'N Yunusov', rating: 1832},
  '*GM_ERIGAISI': {name: 'GM Erigaisi', rating: 2634},
  '*GM_ZVJAGINSEV': {name: 'GM Zvjaginsev', rating: 2539}
};
Object.freeze(PLAYERS);

const regex = /(?=[A-Z])/;
const playerLookup = (player) => {
  if (typeof player !== 'string') {
    return PLAYERS[''];
  }

  const uppercase = player.toUpperCase()
  if (PLAYERS[uppercase]) {
    return PLAYERS[uppercase];
  }

  const parts = player.replace('*', '').split('(')[0].split('_');
  const returnal = [];
  if (parts.length > 1) {
    returnal.push(parts.shift());
  }
  const name = parts.shift();
  returnal.push(name.split(regex)[0].replace('-', ''));

  return {name: returnal.join(' '), rating: null};
};

module.exports = {
  COLOR_WHITE,
  COLOR_BLACK,
  PLAYERS,
  playerLookup
};
